AmazingShop/Controllers/AddressController.cs
using AmazingShop.Models;
using AmazingShop.Models.ViewModels;
using AmazingShop.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AmazingShop.Controllers
{
    [Authorize]
    public class AddressController : Controller
    {
        private readonly IAddressRepository _addressRepository;
        public AddressController(IAddressRepository addressRepository)
        {
            _addressRepository = addressRepository;
        }
        public IActionResult Index()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var addresses = _addressRepository.GetUserAddresses(userId);
            return View(addresses);
        }
        [HttpGet]
        public IActionResult Create(string ctr = null, string act = null)
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            var address = new Address();
            address.UserId = userId;
            var viewModel = new VMWithRedirect<Address>
            {
                Model = address,
                Controller = ctr,
                Action = act
            };
            return View("CreateEdit", viewModel);
        }
        [HttpPost]
        public IActionResult Create(VMWithRedirect<Address> viewModel)
        {
            if (!ModelState.IsValid)
                return View("CreateEdit", viewModel);

            _addressRepository.Add(viewModel.Model);
            if (!String.IsNullOrEmpty(viewModel.Controller)  && !String.IsNullOrEmpty(viewModel.Action))
                return RedirectToAction(viewModel.Action, viewModel.Controller);
            return RedirectToAction("Index");
        }
        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id is null)
                return NotFound();
            var address = _addressRepository.GetById((int)id);
            return View("CreateEdit", address);
        }
        [HttpPost]
        public IActionResult Edit(Address address)
        {
            if (!ModelState.IsValid)
                return View("CreateEdit", address);

            _addressRepository.Update(address);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id is null)
                return NotFound();
            _addressRepository.RemoveById((int)id);
            return RedirectToAction("Index");
        }
    }
}

AmazingShop/Controllers/CartController.cs
using AmazingShop.Models;
using AmazingShop.Models.ViewModels;
using AmazingShop.Repositories;
using AmazingShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AmazingShop.Controllers
{
    [Authorize]
    public class CartController : Controller
    {
        private readonly ICartSessionManager _cartManager;
        private readonly IProductRepository _productRepository;
        private readonly IAddressRepository _addressRepository;
        private readonly IUserRepository _userRepository;
        private readonly IOrderRepository _orderRepository;

        public CartController(ICartSessionManager cartSessionManager,
            IProductRepository productReposistory,
            IUserRepository userRepository,
            IAddressRepository addressRepository,
            IOrderRepository orderRepository)
        {
            _cartManager = cartSessionManager;
            _productRepository = productReposistory;
            _userRepository = userRepository;
            _addressRepository = addressRepository;
            _orderRepository = orderRepository;
        }
        public IActionResult Index()
        {
            var products = GetFullProductsInCart();
            return View(products);
        }
        public IActionResult Remove(int id)
        {
            _cartManager.RemoveProductFromCart(id);
            return RedirectToAction("Index");
        }
        public IActionResult AddOne(int id)
        {
            _cartManager.IncreaseProductQuantity(id, 1);
            return RedirectToAction("Index");
        }
        public IActionResult RemoveOne(int id)
        {
            _cartManager.IncreaseProductQuantity(id, -1);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Order()
        {
            var user = GetCurrentUser();
            var addresses = _addressRepository.GetUserAddresses(user.Id);
            var productsInCart = GetFullProductsInCart();
            var paymentMethods = GetPaymentMethods();
            var viewModel = new NewOrderVM
            {
                User = user,
                Addresses = addresses.Select(a => new SelectListItem { Value = a.Id.ToString(), Text = $"{a.Country}, {a.City}, {a.Street}" }),
                PaymentMethods = paymentMethods,
                Products = productsInCart,
                TotalPrice = GetTotalPrice(productsInCart)
            };
            return View(viewModel);
        }

        [HttpPost]
        public IActionResult Order(NewOrderVM viewModel)
        {
            var products = _cartManager.GetCart();
            var selectedAddress = _addressRepository.GetById(viewModel.SelectedAddressId);
            var header = new OrderHeader
            {
                FullName = $"{viewModel.User.FirstName} {viewModel.User.Surname}",
                Email = viewModel.User.Email,
                PhoneNumber = viewModel.User.PhoneNumber,
                PayymentMethod = viewModel.SelectedPaymentMethod,
                CreatedByUserId = viewModel.User.Id,
                OrderDate = DateTime.Now,
                OrderStatus = ((int)OrderStatuses.Created),
                FinalOrderTotal = viewModel.TotalPrice,
                Country = selectedAddress.Country,
                City = selectedAddress.City,
                Street = selectedAddress.Street,
                BuildingNumber = selectedAddress.BuildingNumber,
                LocalNumber = selectedAddress.LocalNumber,
                ZipPostalCode = selectedAddress.ZipPostalCode
            };
            var orderedProducts = products.Select(p => new OrderedProduct { ProductId = p.ProductId, Quantity = p.Quantity });
            _orderRepository.AddOrder(header, orderedProducts);
            _cartManager.SetCart(new List<ProductInCart>());
            return View("Confirmation", header);
        }

        private IEnumerable<CartProductVM> GetFullProductsInCart()
        {
            var cart = _cartManager.GetCart();
            var products = _productRepository.GetAll();
            var result = cart.Select(p => new CartProductVM
            {
                Product = products.FirstOrDefault(n => n.Id == p.ProductId),
                Quantity = p.Quantity
            });

            foreach (var product in result)
                AddFullImageLinkToProduct(product.Product);

            return result;
        }
        private Product AddFullImageLinkToProduct(Product product)
        {
            var imagePath = _productRepository.ImagePath;
            product.Image = imagePath + product.Image;
            return product;
        }
        private AppUser GetCurrentUser()
        {
            var userId = User.FindFirstValue(ClaimTypes.NameIdentifier);
            return _userRepository.GetById(userId);
        }
        private double GetTotalPrice(IEnumerable<CartProductVM> products)
        {
            double total = 0;
            foreach (var p in products)
                total += (p.Product.Price * p.Quantity);
            return Math.Round(total, 2);
        }

        private IEnumerable<SelectListItem> GetPaymentMethods()
        {
            var methods = Enum.GetValues(typeof(PaymentMethods)).Cast<PaymentMethods>();
            return methods.Select(m => new SelectListItem { Text = m.GetDisplayName(), Value = ((int)m).ToString() });
        }
    }
}

AmazingShop/Controllers/ProductController.cs
using AmazingShop.Models;
using AmazingShop.Models.ViewModels;
using AmazingShop.Repositories;
using AmazingShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AmazingShop.Controllers
{
    [Authorize(Roles = nameof(UserRoles.Admin))]
    public class ProductController : Controller
    {
        private readonly IProductRepository _productRepository;
        private readonly ICategoryRepository _categoryRepository;

        public ProductController(IProductRepository productRepository, ICategoryRepository categoryRepository)
        {
            _productRepository = productRepository;
            _categoryRepository = categoryRepository;
        }

        public IActionResult Index()
        {
            var products = _productRepository.GetAll();
            return View(products);
        }

        [HttpGet]
        public IActionResult Create()
        {
            var viewModel = new ProductCreateEditVM(new Product(), _categoryRepository.GetAll(), _productRepository.ImagePath);
            return View("CreateEdit", viewModel);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create(ProductCreateEditVM viewModel)
        {
            if(!ModelState.IsValid)
                return View("CreateEdit", viewModel);

            var files = HttpContext.Request.Form.Files;
            _productRepository.AddProduct(viewModel.Product, files[0]);
            return RedirectToAction("Index");
        }

        [HttpGet]
        public IActionResult Edit(int? id)
        {
            if (id is null)
                return NotFound();
            var product = _productRepository.GetById((int)id);
            var viewModel = new ProductCreateEditVM(product, _categoryRepository.GetAll(), _productRepository.ImagePath);
            return View("CreateEdit", viewModel);
        }

        [HttpPost]
        [AutoValidateAntiforgeryToken]
        public IActionResult Edit(ProductCreateEditVM viewModel)
        {
            if (!ModelState.IsValid)
                return View("CreateEdit", viewModel);

            var files = HttpContext.Request.Form.Files;

            if (files.Count > 0)
                _productRepository.UpdateProduct(viewModel.Product, files[0]);
            else
                _productRepository.UpdateProduct(viewModel.Product);
            return RedirectToAction("Index");
        }

        public IActionResult Delete(int? id)
        {
            if (id is null)
                return NotFound();

            _productRepository.RemoveById((int)id);
            return RedirectToAction("Index");

        }
    }
}

AmazingShop/Controllers/UserController.cs
using AmazingShop.Models;
using AmazingShop.Repositories;
using AmazingShop.Utility;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Claims;
using System.Threading.Tasks;

namespace AmazingShop.Controllers
{
    [Authorize(Roles = nameof(UserRoles.Admin))]
    public class UserController : Controller
    {
        private readonly IUserRepository _userRepository;
        private readonly UserManager<AppUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public UserController(UserManager<AppUser> userManager, RoleManager<IdentityRole> roleManager, IUserRepository userRepository)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _userRepository = userRepository;
        }
        public IActionResult Index()
        {
            var users = _userRepository.GetAllAsVM();
            return View(users);
        }
        public IActionResult Promote(string id)
        {
            _userRepository.PromoteToAdmin(id);

            return RedirectToAction(nameof(Index));
        }
        public IActionResult Demote(string id)
        {
            _userRepository.DemoteAdmin(id);

            return RedirectToAction(nameof(Index));
        }

    }
}

AmazingShop/Views/Shared/_Layout.cshtml
@using AmazingShop.Utility
@using Microsoft.AspNetCore.Identity
@inject ICartSessionManager cartSessionManager
@inject SignInManager<AppUser> SignInManager

@{
    var cart = cartSessionManager.GetCart();
}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - AmazingShop</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="~/lib/fontawesome/css/all.css" />
</head>
<body style="background-color:lightgray">
    <header>
        <nav class="navbar navbar-expand-lg navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index"><img src="~/images/logo.png" width="60%" /></a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between flex-sm-row-reverse">
                    <partial name="_LoginPartial" />
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Strona Główna</a>
                        </li>
                        @if (User.IsInRole(UserRoles.Admin.ToString()))
                        {
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                Panel Admina
                            </a>
                            <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                <a class="nav-link text-dark" asp-area="" asp-controller="Category" asp-action="Index">Kategorie</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Product" asp-action="Index">Produkty</a>
                                <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index" asp-route-admin="true">Zamówienia</a>
                                <div class="dropdown-divider"></div>
                                <a class="nav-link text-dark" asp-controller="User" asp-action="Index">Użytkownicy</a>
                            </div>
                        </li>
                        }
                        @if (SignInManager.IsSignedIn(User))
                        {
                            <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                                    Panel Użytkownika
                                </a>
                                <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Address" asp-action="Index">Adresy</a>
                                    <a class="nav-link text-dark" asp-area="" asp-controller="Order" asp-action="Index">Zamówienia</a>
                                    <div class="dropdown-divider"></div>
                                </div>
                            </li>
                        }
                        <li>
                            <a asp-action="Index" asp-controller="Cart" class="nav-link">
                                <i class="fas fa-shopping-cart"></i> &nbsp; (@cart.Count)
                            </a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container bg-white card p-md-4 p-sm-1" >
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted bg-white">
        <div class="container">
            &copy; 2022 - AmazingShop - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    <script src="~/lib/sweetalert/sweetalert2.all.min.js"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

AmazingShop/Views/Shared/_ProductCardPartial.cshtml
@model Product


<div class="col-lg-4 col-md-6 pb-4 filter @Model.Category.Name.Replace(' ','_')">
    <div class="card bg-white rounded shadow-sm" style="border:1px solid #222">
        <div class="card-body px-3 pt-3 pb-1 row">
            <div class="col-7"><label class="float-left">@Model.Name</label></div>
            <div class="col-5"><label class="float-right"><span class="text-info h5">@Model.Price.ToString() zł</span></label> </div>
        </div>
        <img class="card-img-top img-fluid d-block mx-auto mb-3" style="max-height: 20em; object-fit: cover" src="@Model.Image" alt="Card image cap">
        <div class="card-body p-1 px-3 row">
            <div class="col-6">
                <span class="badge p-2 border w-100" style="background-color:lavenderblush">@Model.Category.Name</span>
            </div>
            <div class="col-6 border-0">
            </div>
            <div class="col-12 pt-2" style="font-size:13px; text-align:justify">
                <p>@Model.ShortDescription</p>
            </div>
            <div class="col-12 p-1">
                <a asp-action="Details" asp-route-id="@Model.Id" class="btn btn-dark form-control btn-sm p-2" style="height:40px">Szczegóły Produktu</a>
            </div>
        </div>
    </div>
</div>